name: Dump cppreference

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get current date
      id: date
      run: echo "{date}={$(date +'%Y%m%d%H%M')}" >> $GITHUB_STATE

    - name: Generate
      run: |
        make source && tar -Jcvf dump.tar.xz reference
        cp dump.tar.xz reference/dump.tar.xz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: "reference"

    - name: Deploy to raw dumps repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: reference
        destination-github-username: pydongery
        destination-repository-name: cppreference
        user-email: noreply@pydong.org
        user-name: cppreference bot
        target-branch: raw_dumps
        commit-message: Dumped at ${{ env.date }}
