name: Dump cppreference

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate
      run: make source && tar -Jcvf dump.tar.xz reference

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "reference"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dump.tar.xz
