name: Dump cppreference

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Generate
      run: make source && tar -Jcvf dump.tar.xz reference

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: "reference"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        name: Raw dump ${{ steps.date.outputs.date }}
        body: Raw dump of en.cppreference.com retrieved at ${{ steps.date.outputs.date }}
        files: dump.tar.xz
